In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, ReLU, Dropout
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

# Data Collection and Processing

In [21]:
heart_data = pd.read_csv('/content/heart_disease_data.csv')

In [22]:
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [23]:
heart_data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [24]:
heart_data.shape

(303, 14)

In [25]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [26]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [27]:
heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [28]:
heart_data['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

# Splitting the Data into Training data & Test Data

In [29]:
x = heart_data.drop('target', axis=1)
y = heart_data['target']

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=.2, random_state=2)

# Keras 
90%

In [15]:
scaler = StandardScaler()

In [16]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
model = Sequential()
model.add(Dense(100, input_shape=(13,),activation="relu")),
model.add(Dense(128, activation='relu')),
model.add(Dense(64, activation='relu')),
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='Adam', loss='categorical_hinge', metrics=['accuracy'])

In [18]:
# model = Sequential()
# model.add(Dense(100, input_shape=(13,),activation="relu"))
# model.add(Dense(units=64, activation='relu')),
# model.add(Dropout(rate=0.2)),
# model.add(Dense(units=128, activation='relu')),
# model.add(Dropout(rate=0.2)),
# model.add(Dense(units=1, activation='sigmoid'))
# model.compile(optimizer='Adam', loss='categorical_hinge', metrics=['accuracy'])

In [19]:
hist=model.fit(X_train, Y_train,validation_data=(X_test, Y_test), epochs=100)

Epoch 1/100
8/8 [==============================] - 3s 82ms/step - loss: 0.9016 - accuracy: 0.7025 - val_loss: 0.9176 - val_accuracy: 0.8361
Epoch 2/100
8/8 [==============================] - 0s 26ms/step - loss: 0.8049 - accuracy: 0.8099 - val_loss: 0.8128 - val_accuracy: 0.8361
Epoch 3/100
8/8 [==============================] - 0s 14ms/step - loss: 0.7208 - accuracy: 0.8182 - val_loss: 0.7231 - val_accuracy: 0.8689
Epoch 4/100
8/8 [==============================] - 0s 16ms/step - loss: 0.6608 - accuracy: 0.8223 - val_loss: 0.6812 - val_accuracy: 0.8689
Epoch 5/100
8/8 [==============================] - 0s 20ms/step - loss: 0.6305 - accuracy: 0.8264 - val_loss: 0.6629 - val_accuracy: 0.8852
Epoch 6/100
8/8 [==============================] - 0s 18ms/step - loss: 0.6134 - accuracy: 0.8430 - val_loss: 0.6553 - val_accuracy: 0.8852
Epoch 7/100
8/8 [==============================] - 0s 30ms/step - loss: 0.6021 - accuracy: 0.8471 - val_loss: 0.6504 - val_accuracy: 0.8852
Epoch 8/100
8/8 [==============================] - 0s 14ms/step - loss: 0.5938 - accuracy: 0.8554 - val_loss: 0.6446 - val_accuracy: 0.9016
Epoch 9/100
8/8 [==============================] - 0s 15ms/step - loss: 0.5864 - accuracy: 0.8678 - val_loss: 0.6407 - val_accuracy: 0.9016
Epoch 10/100
8/8 [==============================] - 0s 12ms/step - loss: 0.5768 - accuracy: 0.8843 - val_loss: 0.6398 - val_accuracy: 0.9016
Epoch 11/100
8/8 [==============================] - 0s 14ms/step - loss: 0.5678 - accuracy: 0.8884 - val_loss: 0.6399 - val_accuracy: 0.8852
Epoch 12/100
8/8 [==============================] - 0s 19ms/step - loss: 0.5600 - accuracy: 0.9008 - val_loss: 0.6397 - val_accuracy: 0.8852
Epoch 13/100
8/8 [==============================] - 0s 19ms/step - loss: 0.5529 - accuracy: 0.9050 - val_loss: 0.6418 - val_accuracy: 0.9016
Epoch 14/100
8/8 [==============================] - 0s 13ms/step - loss: 0.5471 - accuracy: 0.9132 - val_loss: 0.6401 - val_accuracy: 0.8852
Epoch 15/100
8/8 [==============================] - 0s 17ms/step - loss: 0.5429 - accuracy: 0.9174 - val_loss: 0.6399 - val_accuracy: 0.8852
Epoch 16/100
8/8 [==============================] - 0s 16ms/step - loss: 0.5358 - accuracy: 0.9174 - val_loss: 0.6399 - val_accuracy: 0.9016
Epoch 17/100
8/8 [==============================] - 0s 15ms/step - loss: 0.5334 - accuracy: 0.9132 - val_loss: 0.6380 - val_accuracy: 0.9016
Epoch 18/100
8/8 [==============================] - 0s 12ms/step - loss: 0.5289 - accuracy: 0.9174 - val_loss: 0.6372 - val_accuracy: 0.8852
Epoch 19/100
8/8 [==============================] - 0s 13ms/step - loss: 0.5273 - accuracy: 0.9215 - val_loss: 0.6387 - val_accuracy: 0.9016
Epoch 20/100
8/8 [==============================] - 0s 19ms/step - loss: 0.5257 - accuracy: 0.9215 - val_loss: 0.6357 - val_accuracy: 0.8852
Epoch 21/100
8/8 [==============================] - 0s 17ms/step - loss: 0.5212 - accuracy: 0.9298 - val_loss: 0.6397 - val_accuracy: 0.9016
Epoch 22/100
8/8 [==============================] - 0s 14ms/step - loss: 0.5198 - accuracy: 0.9256 - val_loss: 0.6356 - val_accuracy: 0.9016
Epoch 23/100
8/8 [==============================] - 0s 19ms/step - loss: 0.5167 - accuracy: 0.9298 - val_loss: 0.6353 - val_accuracy: 0.9016
Epoch 24/100
8/8 [==============================] - 0s 21ms/step - loss: 0.5148 - accuracy: 0.9298 - val_loss: 0.6354 - val_accuracy: 0.9016
Epoch 25/100
8/8 [==============================] - 0s 35ms/step - loss: 0.5138 - accuracy: 0.9298 - val_loss: 0.6340 - val_accuracy: 0.9016
Epoch 26/100
8/8 [==============================] - 0s 17ms/step - loss: 0.5128 - accuracy: 0.9298 - val_loss: 0.6344 - val_accuracy: 0.9016
Epoch 27/100
8/8 [==============================] - 0s 12ms/step - loss: 0.5123 - accuracy: 0.9298 - val_loss: 0.6342 - val_accuracy: 0.9016
Epoch 28/100
8/8 [==============================] - 0s 23ms/step - loss: 0.5117 - accuracy: 0.9298 - val_loss: 0.6336 - val_accuracy: 0.9016
Epoch 29/100
8/8 [==============================] - 0s 18ms/step - loss: 0.5117 - accuracy: 0.9298 - val_loss: 0.6324 - val_accuracy: 0.9016
Epoch 30/100
8/8 [==============================] - 0s 20ms/step - loss: 0.5110 - accuracy: 0.9298 - val_loss: 0.6336 - val_accuracy: 0.9016
Epoch 31/100
8/8 [==============================] - 0s 23ms/step - loss: 0.5105 - accuracy: 0.9298 - val_loss: 0.6337 - val_accuracy: 0.9016
Epoch 32/100
8/8 [==============================] - 0s 16ms/step - loss: 0.5102 - accuracy: 0.9298 - val_loss: 0.6324 - val_accuracy: 0.9016
Epoch 33/100
8/8 [==============================] - 0s 24ms/step - loss: 0.5100 - accuracy: 0.9298 - val_loss: 0.6316 - val_accuracy: 0.9016
Epoch 34/100
8/8 [==============================] - 0s 19ms/step - loss: 0.5098 - accuracy: 0.9298 - val_loss: 0.6316 - val_accuracy: 0.9016
Epoch 35/100
8/8 [==============================] - 0s 16ms/step - loss: 0.5097 - accuracy: 0.9298 - val_loss: 0.6317 - val_accuracy: 0.9016
Epoch 36/100
8/8 [==============================] - 0s 12ms/step - loss: 0.5095 - accuracy: 0.9298 - val_loss: 0.6322 - val_accuracy: 0.9016
Epoch 37/100
8/8 [==============================] - 0s 17ms/step - loss: 0.5094 - accuracy: 0.9298 - val_loss: 0.6320 - val_accuracy: 0.9016
Epoch 38/100
8/8 [==============================] - 0s 18ms/step - loss: 0.5093 - accuracy: 0.9298 - val_loss: 0.6318 - val_accuracy: 0.9016
Epoch 39/100
8/8 [==============================] - 0s 20ms/step - loss: 0.5092 - accuracy: 0.9298 - val_loss: 0.6318 - val_accuracy: 0.9016
Epoch 40/100
8/8 [==============================] - 0s 33ms/step - loss: 0.5091 - accuracy: 0.9298 - val_loss: 0.6315 - val_accuracy: 0.9016
Epoch 41/100
8/8 [==============================] - 0s 29ms/step - loss: 0.5091 - accuracy: 0.9298 - val_loss: 0.6316 - val_accuracy: 0.9016
Epoch 42/100
8/8 [==============================] - 0s 14ms/step - loss: 0.5090 - accuracy: 0.9298 - val_loss: 0.6314 - val_accuracy: 0.9016
Epoch 43/100
8/8 [==============================] - 0s 18ms/step - loss: 0.5089 - accuracy: 0.9298 - val_loss: 0.6314 - val_accuracy: 0.9016
Epoch 44/100
8/8 [==============================] - 0s 20ms/step - loss: 0.5087 - accuracy: 0.9298 - val_loss: 0.6312 - val_accuracy: 0.9016
Epoch 45/100
8/8 [==============================] - 0s 23ms/step - loss: 0.5083 - accuracy: 0.9298 - val_loss: 0.6311 - val_accuracy: 0.9016
Epoch 46/100
8/8 [==============================] - 0s 30ms/step - loss: 0.5064 - accuracy: 0.9339 - val_loss: 0.6336 - val_accuracy: 0.9016
Epoch 47/100
8/8 [==============================] - 0s 17ms/step - loss: 0.5059 - accuracy: 0.9339 - val_loss: 0.6380 - val_accuracy: 0.8852
Epoch 48/100
8/8 [==============================] - 0s 13ms/step - loss: 0.5050 - accuracy: 0.9339 - val_loss: 0.6353 - val_accuracy: 0.9016
Epoch 49/100
8/8 [==============================] - 0s 15ms/step - loss: 0.5049 - accuracy: 0.9339 - val_loss: 0.6342 - val_accuracy: 0.9016
Epoch 50/100
8/8 [==============================] - 0s 19ms/step - loss: 0.5048 - accuracy: 0.9339 - val_loss: 0.6351 - val_accuracy: 0.9016
Epoch 51/100
8/8 [==============================] - 0s 18ms/step - loss: 0.5047 - accuracy: 0.9339 - val_loss: 0.6346 - val_accuracy: 0.9016
Epoch 52/100
8/8 [==============================] - 0s 13ms/step - loss: 0.5047 - accuracy: 0.9339 - val_loss: 0.6328 - val_accuracy: 0.9016
Epoch 53/100
8/8 [==============================] - 0s 24ms/step - loss: 0.5046 - accuracy: 0.9339 - val_loss: 0.6326 - val_accuracy: 0.9016
Epoch 54/100
8/8 [==============================] - 0s 18ms/step - loss: 0.5046 - accuracy: 0.9339 - val_loss: 0.6317 - val_accuracy: 0.9016
Epoch 55/100
8/8 [==============================] - 0s 13ms/step - loss: 0.5045 - accuracy: 0.9339 - val_loss: 0.6316 - val_accuracy: 0.9016
Epoch 56/100
8/8 [==============================] - 0s 25ms/step - loss: 0.5045 - accuracy: 0.9339 - val_loss: 0.6318 - val_accuracy: 0.9016
Epoch 57/100
8/8 [==============================] - 0s 19ms/step - loss: 0.5045 - accuracy: 0.9339 - val_loss: 0.6318 - val_accuracy: 0.9016
Epoch 58/100
8/8 [==============================] - 0s 17ms/step - loss: 0.5045 - accuracy: 0.9339 - val_loss: 0.6312 - val_accuracy: 0.9016
Epoch 59/100
8/8 [==============================] - 0s 18ms/step - loss: 0.5045 - accuracy: 0.9339 - val_loss: 0.6311 - val_accuracy: 0.9016
Epoch 60/100
8/8 [==============================] - 0s 18ms/step - loss: 0.5044 - accuracy: 0.9339 - val_loss: 0.6308 - val_accuracy: 0.9016
Epoch 61/100
8/8 [==============================] - 0s 14ms/step - loss: 0.5044 - accuracy: 0.9339 - val_loss: 0.6308 - val_accuracy: 0.9016
Epoch 62/100
8/8 [==============================] - 0s 25ms/step - loss: 0.5044 - accuracy: 0.9339 - val_loss: 0.6307 - val_accuracy: 0.9016
Epoch 63/100
8/8 [==============================] - 0s 16ms/step - loss: 0.5044 - accuracy: 0.9339 - val_loss: 0.6308 - val_accuracy: 0.9016
Epoch 64/100
8/8 [==============================] - 0s 19ms/step - loss: 0.5044 - accuracy: 0.9339 - val_loss: 0.6307 - val_accuracy: 0.9016
Epoch 65/100
8/8 [==============================] - 0s 22ms/step - loss: 0.5044 - accuracy: 0.9339 - val_loss: 0.6308 - val_accuracy: 0.9016
Epoch 66/100
8/8 [==============================] - 0s 23ms/step - loss: 0.5044 - accuracy: 0.9339 - val_loss: 0.6306 - val_accuracy: 0.9016
Epoch 67/100
8/8 [==============================] - 0s 21ms/step - loss: 0.5044 - accuracy: 0.9339 - val_loss: 0.6306 - val_accuracy: 0.9016
Epoch 68/100
8/8 [==============================] - 0s 14ms/step - loss: 0.5044 - accuracy: 0.9339 - val_loss: 0.6307 - val_accuracy: 0.9016
Epoch 69/100
8/8 [==============================] - 0s 27ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6305 - val_accuracy: 0.9016
Epoch 70/100
8/8 [==============================] - 0s 42ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6304 - val_accuracy: 0.9016
Epoch 71/100
8/8 [==============================] - 0s 41ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6303 - val_accuracy: 0.9016
Epoch 72/100
8/8 [==============================] - 0s 29ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6303 - val_accuracy: 0.9016
Epoch 73/100
8/8 [==============================] - 0s 13ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6303 - val_accuracy: 0.9016
Epoch 74/100
8/8 [==============================] - 0s 18ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6303 - val_accuracy: 0.9016
Epoch 75/100
8/8 [==============================] - 0s 14ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6302 - val_accuracy: 0.9016
Epoch 76/100
8/8 [==============================] - 0s 15ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6301 - val_accuracy: 0.9016
Epoch 77/100
8/8 [==============================] - 0s 24ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6302 - val_accuracy: 0.9016
Epoch 78/100
8/8 [==============================] - 0s 20ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6303 - val_accuracy: 0.9016
Epoch 79/100
8/8 [==============================] - 0s 25ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6303 - val_accuracy: 0.9016
Epoch 80/100
8/8 [==============================] - 0s 19ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6301 - val_accuracy: 0.9016
Epoch 81/100
8/8 [==============================] - 0s 18ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6301 - val_accuracy: 0.9016
Epoch 82/100
8/8 [==============================] - 0s 17ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6301 - val_accuracy: 0.9016
Epoch 83/100
8/8 [==============================] - 0s 27ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6302 - val_accuracy: 0.9016
Epoch 84/100
8/8 [==============================] - 0s 13ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6299 - val_accuracy: 0.9016
Epoch 85/100
8/8 [==============================] - 0s 13ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6300 - val_accuracy: 0.9016
Epoch 86/100
8/8 [==============================] - 0s 14ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6300 - val_accuracy: 0.9016
Epoch 87/100
8/8 [==============================] - 0s 29ms/step - loss: 0.5043 - accuracy: 0.9339 - val_loss: 0.6299 - val_accuracy: 0.9016
Epoch 88/100
8/8 [==============================] - 0s 17ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6299 - val_accuracy: 0.9016
Epoch 89/100
8/8 [==============================] - 0s 26ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6298 - val_accuracy: 0.9016
Epoch 90/100
8/8 [==============================] - 0s 19ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6299 - val_accuracy: 0.9016
Epoch 91/100
8/8 [==============================] - 0s 10ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6298 - val_accuracy: 0.9016
Epoch 92/100
8/8 [==============================] - 0s 7ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6298 - val_accuracy: 0.9016
Epoch 93/100
8/8 [==============================] - 0s 7ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6297 - val_accuracy: 0.9016
Epoch 94/100
8/8 [==============================] - 0s 7ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6297 - val_accuracy: 0.9016
Epoch 95/100
8/8 [==============================] - 0s 8ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6298 - val_accuracy: 0.9016
Epoch 96/100
8/8 [==============================] - 0s 8ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6299 - val_accuracy: 0.9016
Epoch 97/100
8/8 [==============================] - 0s 8ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6297 - val_accuracy: 0.9016
Epoch 98/100
8/8 [==============================] - 0s 8ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6297 - val_accuracy: 0.9016
Epoch 99/100
8/8 [==============================] - 0s 7ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6296 - val_accuracy: 0.9016
Epoch 100/100
8/8 [==============================] - 0s 8ms/step - loss: 0.5042 - accuracy: 0.9339 - val_loss: 0.6296 - val_accuracy: 0.9016

In [20]:
prediction = (model.predict(X_test) >= 0.5)
print(classification_report(Y_test.values, prediction))

2/2 [==============================] - 0s 7ms/step
              precision    recall  f1-score   support

           0       0.96      0.84      0.90        32
           1       0.85      0.97      0.90        29

    accuracy                           0.90        61
   macro avg       0.91      0.90      0.90        61
weighted avg       0.91      0.90      0.90        61